name: CI - Circular Buffer Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ cmake libgtest-dev build-essential

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTING=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel 4

    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure

    - name: Run demos
      working-directory: ./build
      run: |
        ./demo
        ./demo_mutex
        ./demo_bulk
        ./demo_overwrite
        ./demo_enhanced
        ./demo_stats
        ./demo_timeout

  linux-clang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang clang-tidy cmake libgtest-dev build-essential

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DBUILD_TESTING=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel 4

    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure

    - name: Run demos
      working-directory: ./build
      run: |
        ./demo
        ./demo_mutex
        ./demo_bulk
        ./demo_overwrite
        ./demo_enhanced
        ./demo_stats
        ./demo_timeout

  macos-clang:
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: brew install cmake googletest

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTING=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel 4

    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure

    - name: Run demos
      working-directory: ./build
      run: |
        ./demo
        ./demo_mutex
        ./demo_bulk
        ./demo_overwrite
        ./demo_enhanced
        ./demo_stats
        ./demo_timeout